CREATE TABLE `learning_session_evidence` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `evidence_id` varchar(255) NOT NULL,
  `course_id` bigint NOT NULL,
  `lecture_id` bigint NOT NULL,
  `material_id` bigint DEFAULT NULL,
  `student_id` bigint NOT NULL,
  `session_id` bigint NOT NULL,
  `page_number` int DEFAULT NULL,
  `event_type` varchar(100) DEFAULT NULL,
  `quiz_type` varchar(100) DEFAULT NULL,
  `score_ratio` double DEFAULT NULL,
  `passed` bit(1) DEFAULT NULL,
  `weak_concepts_json` json DEFAULT NULL,
  `wrong_items_json` json DEFAULT NULL,
  `evidence_json` json DEFAULT NULL,
  `occurred_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_learning_session_evidence_evidence_id` (`evidence_id`),
  KEY `idx_learning_session_evidence_student_course_time` (`student_id`, `course_id`, `occurred_at`),
  KEY `idx_learning_session_evidence_session` (`session_id`),
  KEY `idx_learning_session_evidence_lecture_student` (`lecture_id`, `student_id`),
  KEY `fk_learning_session_evidence_course` (`course_id`),
  KEY `fk_learning_session_evidence_material` (`material_id`),
  CONSTRAINT `fk_learning_session_evidence_course` FOREIGN KEY (`course_id`) REFERENCES `courses` (`course_id`),
  CONSTRAINT `fk_learning_session_evidence_lecture` FOREIGN KEY (`lecture_id`) REFERENCES `lectures` (`lecture_id`),
  CONSTRAINT `fk_learning_session_evidence_material` FOREIGN KEY (`material_id`) REFERENCES `material` (`material_id`),
  CONSTRAINT `fk_learning_session_evidence_student` FOREIGN KEY (`student_id`) REFERENCES `students` (`student_id`),
  CONSTRAINT `fk_learning_session_evidence_session` FOREIGN KEY (`session_id`) REFERENCES `learning_chat_sessions` (`chat_session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
