CREATE TABLE `learning_integrated_evidence` (
  `learning_evidence_id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `event_kind` varchar(100) DEFAULT NULL,
  `page_number` int DEFAULT NULL,
  `coverage_start_page` int DEFAULT NULL,
  `coverage_end_page` int DEFAULT NULL,
  `quiz_id` varchar(255) DEFAULT NULL,
  `quiz_type` varchar(100) DEFAULT NULL,
  `score_ratio` double DEFAULT NULL,
  `passed` bit(1) DEFAULT NULL,
  `weak_concepts` json DEFAULT NULL,
  `missed_questions` json DEFAULT NULL,
  `diagnostic_prompt` text,
  `raw_evidence` json DEFAULT NULL,
  `chat_session_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `lecture_id` bigint NOT NULL,
  `material_id` bigint DEFAULT NULL,
  PRIMARY KEY (`learning_evidence_id`),
  KEY `idx_learning_evidence_user_lecture_material` (`user_id`, `lecture_id`, `material_id`),
  KEY `idx_learning_evidence_lecture_user` (`lecture_id`, `user_id`),
  KEY `idx_learning_evidence_session` (`chat_session_id`),
  KEY `idx_learning_evidence_created` (`created_at`),
  KEY `fk_learning_evidence_material` (`material_id`),
  CONSTRAINT `fk_learning_evidence_session` FOREIGN KEY (`chat_session_id`) REFERENCES `learning_chat_sessions` (`chat_session_id`),
  CONSTRAINT `fk_learning_evidence_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`),
  CONSTRAINT `fk_learning_evidence_lecture` FOREIGN KEY (`lecture_id`) REFERENCES `lectures` (`lecture_id`),
  CONSTRAINT `fk_learning_evidence_material` FOREIGN KEY (`material_id`) REFERENCES `material` (`material_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
